// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// THIS IS A PLACEHOLDER FILE.
/// PLEASE RUN `flutterfire configure` TO GENERATE YOUR OWN `firebase_options.dart`
/// AND REPLACE THIS FILE WITH THE GENERATED ONE.
///
/// A default FirebaseOptions instance to use with Real-time Database instances.
///
/// Must be configured with a real project ID.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgLMbAcj6_7jxJzIib74x2-G7S7WmcOI0',
    appId: '1:1036643763303:android:c9292f578b335dd9ac80c2',
    messagingSenderId: '1036643763303',
    projectId: 'kouzinti-40bcd',
    storageBucket: 'kouzinti-40bcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvu7EHEw9day5u2aBP30FbDAi-RlgFLn8',
    appId: '1:1036643763303:ios:4217ac31d44fea36ac80c2',
    messagingSenderId: '1036643763303',
    projectId: 'kouzinti-40bcd',
    storageBucket: 'kouzinti-40bcd.firebasestorage.app',
    iosBundleId: 'com.example.kouzinti',
  );

} 